#!/bin/bash

# Script de Testes Interativos PWA
# Team Nascimento BJJ

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🧪 Guia Interativo de Testes PWA                       ║"
echo "║     Team Nascimento BJJ                                    ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""
echo "✅ Servidor rodando em: http://localhost:4173"
echo ""
echo "📋 Escolha um teste para começar:"
echo ""
echo "   1️⃣  Verificar Service Worker & Manifest"
echo "   2️⃣  Prompt de Instalação (Install App)"
echo "   3️⃣  Cache Storage"
echo "   4️⃣  TESTE OFFLINE (Mais Importante!)"
echo "   5️⃣  Pagamentos Offline"
echo "   6️⃣  Vídeos Offline"
echo "   7️⃣  Notificações Push"
echo "   8️⃣  Performance (Lighthouse)"
echo "   9️⃣  Teste em Celular"
echo "   🔟  Sincronização Automática"
echo "   1️⃣1️⃣ Debugging Console"
echo "   1️⃣2️⃣ Verificar Atualizações"
echo ""
echo "   📖 Abrir Guia Completo"
echo "   🌐 Abrir App"
echo "   ❌ Sair"
echo ""

while true; do
    read -p "Escolha uma opção: " choice

    case $choice in
        1)
            echo ""
            echo "🔍 TESTE 1: Verificar Service Worker & Manifest"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Passos:"
            echo "  1. Abra DevTools: F12"
            echo "  2. Vá para aba: Application"
            echo "  3. Clique em: Manifest (no menu esquerdo)"
            echo ""
            echo "O que você deve ver:"
            echo "  ✅ Name: Team Nascimento BJJ"
            echo "  ✅ Start URL: /"
            echo "  ✅ Display: standalone"
            echo "  ✅ Icons: 4 ícones listados"
            echo ""
            echo "Também verifique Service Workers:"
            echo "  1. Application → Service Workers"
            echo "  2. Status deve ser: Running (verde)"
            echo ""
            echo "Abra o app em uma nova aba: http://localhost:4173"
            echo ""
            ;;
        2)
            echo ""
            echo "📲 TESTE 2: Prompt de Instalação (Install App)"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Passos:"
            echo "  1. Acesse: http://localhost:4173"
            echo "  2. Procure ícone de instalação:"
            echo "     - Chrome/Edge: Ícone na barra de endereço"
            echo "     - Ou: Menu (⋮) → 'Instalar app' ou 'Install app'"
            echo "  3. Clique para instalar"
            echo ""
            echo "O que acontece:"
            echo "  ✅ Prompt de instalação aparece"
            echo "  ✅ Após confirmar: App abre em janela separada"
            echo "  ✅ Atalho criado na tela inicial"
            echo ""
            ;;
        3)
            echo ""
            echo "💾 TESTE 3: Cache Storage"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Passos:"
            echo "  1. DevTools: F12"
            echo "  2. Abra aba: Application"
            echo "  3. Menu esquerdo: Storage → Cache Storage"
            echo ""
            echo "O que você deve ver:"
            echo "  ✅ google-fonts-cache"
            echo "  ✅ cdn-cache"
            echo "  ✅ api-cache"
            echo "  ✅ videos-cache"
            echo "  ✅ sw:.../sw.js (Service Worker cache)"
            echo ""
            echo "Clique em cada cache para ver o conteúdo armazenado!"
            echo ""
            ;;
        4)
            echo ""
            echo "🌐 TESTE 4: MODO OFFLINE (MAIS IMPORTANTE!)"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Passos:"
            echo "  1. Acesse: http://localhost:4173"
            echo "  2. DevTools: F12"
            echo "  3. Aba: Network (no topo)"
            echo "  4. Procure checkbox 'Offline'"
            echo "     (Se não ver, procure em 'No throttling')"
            echo "  5. MARQUE 'Offline' ✓"
            echo "  6. Recarregue a página: Ctrl + R"
            echo ""
            echo "O que deve acontecer:"
            echo "  ✅ Página CONTINUA funcionando!"
            echo "  ✅ Nenhum erro aparece"
            echo "  ✅ Pode navegar entre abas"
            echo ""
            echo "VERIFICAÇÕES:"
            echo "  📊 Na aba Network, veja os requests"
            echo "     → Procure por 'from cache' ou status 200"
            echo "  🚫 Não deve haver requests vermelhos (erros)"
            echo ""
            echo "Teste navegação:"
            echo "  ☐ Clique em 'Dashboard'"
            echo "  ☐ Clique em 'Alunos'"
            echo "  ☐ Clique em 'Biblioteca'"
            echo "  ☐ Tudo deve funcionar!"
            echo ""
            ;;
        5)
            echo ""
            echo "💳 TESTE 5: Pagamentos Offline"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Pré-requisito:"
            echo "  • Você já integrou PaymentForm.vue em uma página"
            echo ""
            echo "Passos:"
            echo "  1. Ative Modo Offline (DevTools → Network → Offline ✓)"
            echo "  2. Vá para página com formulário de pagamento"
            echo "  3. Preencha:"
            echo "     - Valor: 199.90"
            echo "     - Aluno: selecione algum"
            echo "     - Método: Cartão de Crédito"
            echo "  4. Clique: 'Confirmar Pagamento'"
            echo ""
            echo "O que deve aparecer:"
            echo "  ✅ Aviso amarelo: 'Modo Offline'"
            echo "  ✅ Botão muda para: 'Processando...'"
            echo "  ✅ Notificação: 'Pagamento armazenado!'"
            echo "  ✅ Mensagem: 'Será sincronizado quando conectado'"
            echo ""
            echo "Verificar armazenamento:"
            echo "  1. DevTools → Storage → IndexedDB"
            echo "  2. Selecione: nascimento-bjj"
            echo "  3. Abra: payments"
            echo "  ✅ Você deve ver sua entrada de pagamento!"
            echo ""
            echo "Sincronizar após conectar:"
            echo "  1. Desmarque 'Offline' em Network"
            echo "  2. Recarregue a página"
            echo "  3. Aguarde 2-3 segundos"
            echo "  ✅ Notificação: 'Pagamento sincronizado!'"
            echo "  ✅ IndexedDB: entrada desaparece (foi pro servidor)"
            echo ""
            ;;
        6)
            echo ""
            echo "🎥 TESTE 6: Vídeos Offline"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Pré-requisito:"
            echo "  • Você já integrou VideoLibraryOffline.vue em uma página"
            echo ""
            echo "Passos:"
            echo "  1. Conexão ONLINE (desmarque Offline)"
            echo "  2. Vá para página com biblioteca de vídeos"
            echo "  3. Procure por um vídeo"
            echo "  4. Clique botão: 'Baixar'"
            echo ""
            echo "Download em progresso:"
            echo "  1. DevTools → Network"
            echo "  2. Você vai ver arquivo .mp4 sendo baixado"
            echo "  ✅ Status: Em progresso..."
            echo "  3. Após terminar: Notificação 'Vídeo baixado!'"
            echo "  ✅ Botão muda para: 'Remover'"
            echo ""
            echo "Assistir offline:"
            echo "  1. Ative Modo Offline (Network → Offline ✓)"
            echo "  2. Clique: 'Assistir' no vídeo"
            echo "  ✅ Player abre"
            echo "  ✅ Vídeo reproduz perfeitamente!"
            echo ""
            echo "Verificar Cache:"
            echo "  1. DevTools → Storage → Cache Storage"
            echo "  2. Abra: videos-cache"
            echo "  ✅ Você deve ver o .mp4 armazenado"
            echo ""
            ;;
        7)
            echo ""
            echo "🔔 TESTE 7: Notificações Push"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Primeira vez:"
            echo "  1. Acesse http://localhost:4173"
            echo "  2. Navegador pode pedir: 'Permitir notificações?'"
            echo "  3. Clique: 'Permitir' (não bloqueie!)"
            echo ""
            echo "Se já bloqueou:"
            echo "  1. DevTools → Application → Manifest"
            echo "  2. Clique no botão ao lado de 'Notifications'"
            echo "  3. Selecione: 'Allow'"
            echo ""
            echo "Teste notificações:"
            echo "  1. Realize alguma ação (ex: pagar, baixar vídeo)"
            echo "  2. Verifique notificação no canto da tela"
            echo "  ✅ Deve aparecer notificação"
            echo ""
            echo "Ver notificações no DevTools:"
            echo "  1. DevTools → Application"
            echo "  2. Menu esquerdo: Service Workers"
            echo "  3. Em cima: 'Inspection' ou similar"
            echo "  4. Verá lista de notificações enviadas"
            echo ""
            ;;
        8)
            echo ""
            echo "📊 TESTE 8: Performance (Lighthouse)"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Rodando Lighthouse:"
            echo "  1. Acesse http://localhost:4173"
            echo "  2. DevTools: F12"
            echo "  3. Procure aba: Lighthouse"
            echo "     (Se não tiver, vá em Menu (⋮) → More tools → Lighthouse)"
            echo "  4. Selecione:"
            echo "     - Device: Mobile"
            echo "     - Category: Progressive Web App"
            echo "  5. Clique: 'Analyze page load'"
            echo "  6. Aguarde análise (30-60 segundos)"
            echo ""
            echo "Resultado esperado:"
            echo "  ✅ PWA Score: > 90 (ideal)"
            echo "  ✅ Performance: > 85"
            echo "  ✅ Accessibility: > 90"
            echo "  ✅ Best Practices: > 90"
            echo ""
            echo "Se score baixo:"
            echo "  • Podem faltar ícones em public/"
            echo "  • Verifique console por erros"
            echo "  • Veja 'Opportunities' no relatório"
            echo ""
            ;;
        9)
            echo ""
            echo "📱 TESTE 9: Teste em Dispositivo Celular"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Pré-requisito:"
            echo "  • Celular e PC na mesma rede WiFi"
            echo "  • Servidor rodando em http://localhost:4173"
            echo ""
            echo "Passo 1: Descobrir IP da sua máquina"
            echo "  (No Windows CMD ou PowerShell)"
            echo "  $ ipconfig"
            echo ""
            echo "  Procure por:"
            echo "  'IPv4 Address . . . . . : 192.168.X.X'"
            echo ""
            echo "Passo 2: No celular"
            echo "  1. Abra navegador"
            echo "  2. Acesse: http://192.168.X.X:4173"
            echo "  (substitua o X pelo seu IP)"
            echo ""
            echo "Passo 3: Instalar app"
            echo "  ANDROID (Chrome):"
            echo "    • Menu (⋮) → Instalar app"
            echo "    • Confirme"
            echo "    • App aparece na tela inicial ✅"
            echo ""
            echo "  iPHONE (Safari):"
            echo "    • Compartilhar (canto inf direito)"
            echo "    • Adicionar à tela inicial"
            echo "    • Confirme"
            echo "    • App aparece como ícone ✅"
            echo ""
            echo "Passo 4: Testar offline"
            echo "  1. Ativa modo avião ✈️"
            echo "  2. Abre app"
            echo "  ✅ Deve funcionar completamente!"
            echo "  3. Desativa modo avião"
            echo "  ✅ Dados sincronizam"
            echo ""
            ;;
        10)
            echo ""
            echo "🔄 TESTE 10: Sincronização Automática"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Cenário:"
            echo "  1. Ative Offline (Network → Offline ✓)"
            echo "  2. Realize ações (pagamentos, etc)"
            echo "  3. Dados ficam pendentes"
            echo "  4. Desative Offline"
            echo "  5. Dados sincronizam automaticamente"
            echo ""
            echo "Verificar sincronização:"
            echo "  1. DevTools → Console"
            echo "  2. Desmarque 'Offline'"
            echo "  3. Você deve ver logs como:"
            echo "     [Service Worker] Sincronizando pagamentos..."
            echo "     ✅ Pagamento sincronizado!"
            echo ""
            echo "  4. IndexedDB → nascimento-bjj → payments"
            echo "  ✅ Entradas desaparecem (foram para servidor)"
            echo ""
            echo "  5. Deve haver notificação:"
            echo "     'Pagamento sincronizado com sucesso!'"
            echo ""
            ;;
        11)
            echo ""
            echo "🐛 TESTE 11: Debugging Console"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Verificar logs:"
            echo "  1. Acesse http://localhost:4173"
            echo "  2. DevTools: F12"
            echo "  3. Aba: Console"
            echo ""
            echo "Você deve ver:"
            echo "  ✅ '[Service Worker] Instalando...'"
            echo "  ✅ '[Service Worker] Ativando...'"
            echo "  ✅ '[Service Worker] Carregado com sucesso!'"
            echo "  ✅ '✅ Service Worker registrado'"
            echo "  ✅ '📲 Prompt de instalação disponível'"
            echo ""
            echo "NÃO deve haver:"
            echo "  ❌ Erros em vermelho"
            echo "  ❌ CORS errors"
            echo "  ❌ 404 Not Found"
            echo ""
            echo "Se tiver erros:"
            echo "  1. Anote mensagem de erro"
            echo "  2. Procure no arquivo correspondente"
            echo "  3. Verifique sintaxe"
            echo ""
            ;;
        12)
            echo ""
            echo "⚡ TESTE 12: Verificar Atualizações"
            echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
            echo ""
            echo "Sistema de updates automáticos:"
            echo "  1. Acesse http://localhost:4173"
            echo "  2. DevTools → Console"
            echo "  3. Recarregue página (Ctrl + R)"
            echo "  4. Você deve ver:"
            echo "     'Checking for updates...'"
            echo ""
            echo "Se há nova versão:"
            echo "  1. Service Worker detecta"
            echo "  2. Baixa em background"
            echo "  3. Próxima vez que abrir:"
            echo "     'New version available!'"
            echo "  4. Pode atualizar manualmente ou automático"
            echo ""
            echo "Testar atualizações:"
            echo "  1. Faça uma mudança no código"
            echo "  2. npm run build"
            echo "  3. Recarregue página no navegador"
            echo "  4. Service Worker detecta mudança"
            echo "  5. Oferece atualizar"
            echo ""
            ;;
        *)
            if [[ "$choice" == "guia" ]]; then
                echo ""
                echo "📖 Abrindo guia completo..."
                echo "Veja arquivo: TESTING_GUIDE.md"
                echo ""
            elif [[ "$choice" == "app" ]]; then
                echo ""
                echo "🌐 Abrindo app no navegador..."
                echo "http://localhost:4173"
                echo ""
            elif [[ "$choice" == "exit" ]] || [[ "$choice" == "sair" ]]; then
                echo ""
                echo "👋 Até logo! Boa sorte com os testes!"
                echo ""
                break
            else
                echo ""
                echo "❌ Opção inválida. Tente novamente."
                echo ""
            fi
            ;;
    esac
done
